"""Private native transport. Public wrappers define service-specific results."""

from collections.abc import Mapping
from typing import Any

def start(operation: str, options: str, buffers: Mapping[str, object] | None = None) -> object: ...
def poll(handle: object, timeout: float, consume: bool = True) -> str: ...
def close(handle: object) -> None: ...
def clipboard(operation: str, input: object = None, *, local_only: bool = False,
              expires_in: float | None = None) -> Any: ...
